### ISSUE TITLE
Code Smell - Clear naming of variables

### ISSUE THREAD

**Issue by jkoolz** [jackbtroop62/AR-Space#47]
Lower case m before items is confusing - simply use their names.
You do not have to use suggested names, but these would be easier to understand.

Line 22 - mTextMessage => textMessage
and change subsequent mTextMessage variables accordingly

Line 24 - mOnNavigationItemSelectedListener => onNavigationItemSelectedListener
and change subsequent mOnNavigationItemSelectedListener variables accordingly

Line 47 - mTwoPane => twoPane
and change subsequent mTwoPane variables accordingly

Line 90 - mParentActivity => parentActivity
and change subsequent mParentActivity variables accordingly

Line 91 - mValues => values
and change subsequent mValues variables accordingly

Line 92 - mTwoPane => twoPane
and change subsequent mTwoPane variables accordingly

Line 156 - mIdView => idView
and change subsequent mIdView variables accordingly

Line 157 - mContentView => contentView
and change subsequent mContentView variables accordingly

**Comment by C-Deck** [comment]
These have been changed to make them more clear.
